# Generated by Django 3.2.7 on 2021-12-10 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('status', models.CharField(max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xmls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFile', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(max_length=255)),
                ('xml', models.CharField(max_length=20000)),
                ('status', models.CharField(max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMaquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMaquina', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=1)),
                ('dtUltVezOnLine', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.SlugField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCompraVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('corretora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('simbolo', models.CharField(max_length=255)),
                ('ambiente', models.CharField(max_length=1, blank=True, null=True)),
                ('nomeRobo', models.CharField(max_length=20, blank=True, null=True)),
                ('preco_compra', models.FloatField(blank=True, null=True)),
                ('preco_venda', models.FloatField(blank=True, null=True)),
                ('preco_loss', models.FloatField(blank=True, null=True)),
                ('preco_gain', models.FloatField(blank=True, null=True)),
                ('qtdContratos', models.IntegerField(blank=True, null=True)),
                ('data_compra', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('data_venda', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=1, blank=True, null=True)),
                ('perfil', models.CharField(max_length=1, blank=True, null=True)),
                ('tipo', models.CharField(max_length=1, blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),           
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.IntegerField(blank=True, null=True )),
                ('senha', models.CharField(max_length=100, blank=True, null=True)),
                ('aplicativo', models.CharField(max_length=50, blank=True, null=True)),
                ('server', models.CharField(max_length=50, blank=True, null=True)),
                ('empresa', models.CharField(max_length=50, blank=True, null=True)),
                ('ambiente', models.CharField(max_length=1, blank=True, null=True)),
                ('moeda', models.CharField(max_length=10, blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('capitalLig', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), 
                ('ordem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('corretora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),       
                ('status', models.CharField(max_length=1, blank=True, null=True )),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
