# Generated by Django 3.2.7 on 2021-12-19 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordercompravenda',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ordercompravenda',
            name='corretora_id',
        ),
        migrations.RemoveField(
            model_name='orderenvio',
            name='status',
        ),
        migrations.AddField(
            model_name='ordercompravenda',
            name='ticket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderenvio',
            name='periodo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemstatus',
            name='corretora_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.corretora'),
        ),
        migrations.AlterField(
            model_name='ordemstatus',
            name='ordem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.orderenvio'),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='ordem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.orderenvio'),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='simbolo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='simbolo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RequicaoEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.estrategias')),
                ('ordem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.orderenvio')),
            ],
        ),
    ]
