# Generated by Django 3.2.8 on 2022-03-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustonResponse008',
            fields=[
                ('id', models.IntegerField(db_column=False, primary_key=True, serialize=False)),
                ('corretora_id_id', models.IntegerField(blank=True, db_column=False, null=True)),
                ('robo_id_id', models.IntegerField(blank=True, db_column=False, null=True)),
                ('urlPrincipal', models.CharField(blank=True, db_column=False, max_length=255, null=True)),
                ('dataConf', models.DateTimeField(auto_now_add=True, db_column=False, null=True)),
                ('loteWin', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('loteWdo', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('loteB3', models.FloatField(blank=True, db_column=False, default=0, max_length=1, null=True)),
                ('gainDiario', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('lossDiario', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('lossWin', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('gainWin', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('lossWdo', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('gainWdo', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('lossB3', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('gainB3', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('seguranca', models.FloatField(blank=True, db_column=False, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_column=False, null=True)),
                ('updated', models.DateTimeField(auto_now=True, db_column=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='seguranca',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='loteB3',
            field=models.FloatField(blank=True, default=0, max_length=1, null=True),
        ),
    ]
