# Generated by Django 3.2.8 on 2022-03-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220315_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoes',
            name='segurancaWDO',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse008',
            name='segurancaWDO',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
