# Generated by Django 3.2.7 on 2021-12-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211213_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercompravenda',
            name='periodo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderenvio',
            name='periodo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
