# Generated by Django 3.2.8 on 2021-12-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211219_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercompravenda',
            name='corretora_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.corretora'),
            preserve_default=False,
        ),
    ]
