# Generated by Django 3.2.7 on 2021-12-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211213_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercompravenda',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='ordercompravenda',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='orderenvio',
            name='ambiente',
        ),
        migrations.AddField(
            model_name='ordercompravenda',
            name='perfil',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ordercompravenda',
            name='ticket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='ambiente',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='aplicativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='senha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estrategias',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='estrategias',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estrategias',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estrategias',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='estrategias',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='ambiente',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='corretora_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.corretora'),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='data_compra',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='data_venda',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='nomeRobo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='ordem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.orderenvio'),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='preco_compra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='preco_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='preco_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='preco_venda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='qtdContratos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='simbolo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='periodo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='simbolo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
