# Generated by Django 3.2.8 on 2022-04-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ordercompravenda_lucro'),
    ]

    operations = [
        migrations.AddField(
            model_name='custonresponse005',
            name='lucro',
            field=models.FloatField(blank=True, db_column=False, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse005',
            name='lucro1',
            field=models.FloatField(blank=True, db_column=False, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse005',
            name='lucro2',
            field=models.FloatField(blank=True, db_column=False, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse005',
            name='lucro3',
            field=models.FloatField(blank=True, db_column=False, null=True),
        ),
    ]
