# Generated by Django 3.2.8 on 2021-12-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_ordercompravenda_corretora_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercompravenda',
            name='corretora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CustonResponse001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, db_column=False, max_length=1, null=True)),
                ('corretora', models.CharField(blank=True, db_column=False, max_length=1, null=True)),
                ('corretora_id', models.ForeignKey(db_column=False, on_delete=django.db.models.deletion.CASCADE, to='blog.corretora')),
                ('ordem_id', models.ForeignKey(db_column=False, on_delete=django.db.models.deletion.CASCADE, to='blog.orderenvio')),
            ],
        ),
    ]
