# Generated by Django 3.2.7 on 2021-12-16 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211215_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercompravenda',
            name='corretora_id',
        ),
        migrations.RemoveField(
            model_name='orderenvio',
            name='status',
        ),
        migrations.CreateModel(
            name='OrdemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('corretora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.corretora')),
                ('ordem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.orderenvio')),
            ],
        ),
    ]
