# Generated by Django 3.2.7 on 2021-12-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211216_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretora',
            name='capitalLig',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corretora',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corretora',
            name='moeda',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='corretora',
            name='server',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
