# Generated by Django 3.2.8 on 2022-05-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220403_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesPorEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(blank=True, max_length=200, null=True)),
                ('dataConf', models.DateTimeField(auto_now_add=True, null=True)),
                ('lote', models.FloatField(blank=True, default=0, null=True)),
                ('gainDiario', models.FloatField(blank=True, default=0, null=True)),
                ('lossDiario', models.FloatField(blank=True, default=0, null=True)),
                ('seguranca', models.FloatField(blank=True, default=0, null=True)),
                ('loss', models.FloatField(blank=True, default=0, null=True)),
                ('gain', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('corretora_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.corretora')),
                ('estr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.estrategias')),
            ],
        ),
    ]
