# Generated by Django 3.2.8 on 2022-01-05 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211223_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustonResponse002',
            fields=[
                ('id', models.IntegerField(db_column=False, primary_key=True, serialize=False)),
                ('simbolo', models.CharField(blank=True, db_column=False, max_length=10, null=True)),
                ('valor', models.FloatField(blank=True, db_column=False, null=True)),
                ('periodo', models.IntegerField(blank=True, db_column=False, null=True)),
                ('data', models.DateTimeField(blank=True, db_column=False, null=True)),
                ('tipo', models.CharField(blank=True, db_column=False, max_length=1, null=True)),
                ('created', models.DateTimeField(blank=True, db_column=False, null=True)),
                ('updated', models.DateTimeField(blank=True, db_column=False, null=True)),
                ('nome', models.CharField(blank=True, db_column=False, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustonResponse004',
            fields=[
                ('id', models.IntegerField(db_column=False, primary_key=True, serialize=False)),
                ('simbolo', models.CharField(blank=True, db_column=False, max_length=10, null=True)),
                ('valor', models.FloatField(blank=True, db_column=False, null=True)),
                ('periodo', models.IntegerField(blank=True, db_column=False, null=True)),
                ('data', models.DateTimeField(blank=True, db_column=False, null=True)),
                ('tipo', models.CharField(blank=True, db_column=False, max_length=1, null=True)),
                ('created', models.DateTimeField(blank=True, db_column=False, null=True)),
                ('updated', models.DateTimeField(blank=True, db_column=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustonResponse005',
            fields=[
                ('id', models.IntegerField(db_column=False, primary_key=True, serialize=False)),
                ('usuario', models.IntegerField(blank=True, db_column=False, null=True)),
                ('ordem_abertas_hoje', models.IntegerField(blank=True, db_column=False, null=True)),
                ('ordem_abertas_total', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_started', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_placed', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_canceled', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_partial', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_filled', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_rejected', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_expired', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_request_add', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_request_modify', models.IntegerField(blank=True, db_column=False, null=True)),
                ('order_state_request_cancel', models.IntegerField(blank=True, db_column=False, null=True)),
                ('ordem_erro', models.IntegerField(blank=True, db_column=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustonResponse006',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_id_id', models.IntegerField(db_column=False)),
                ('nome', models.CharField(blank=True, db_column=False, max_length=200, null=True)),
                ('descricao', models.CharField(blank=True, db_column=False, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordercompravenda',
            name='corretora',
        ),
        migrations.AddField(
            model_name='corretora',
            name='roboEnvioOrdem',
            field=models.CharField(blank=True, default='F', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='corretora',
            name='roboRecebimentoOrdem',
            field=models.CharField(blank=True, default='F', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='corretora',
            name='roboUpdateOrdem',
            field=models.CharField(blank=True, default='F', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_column=False, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='data_compra',
            field=models.DateTimeField(blank=True, db_column=False, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True, db_column=False, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='preco_compra',
            field=models.FloatField(blank=True, db_column=False, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='preco_gain',
            field=models.FloatField(blank=True, db_column=False, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='preco_loss',
            field=models.FloatField(blank=True, db_column=False, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='preco_venda',
            field=models.FloatField(db_column=False, default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='simbolo',
            field=models.CharField(db_column=False, default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='ticket',
            field=models.IntegerField(db_column=False, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custonresponse001',
            name='tipo',
            field=models.CharField(db_column=False, default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corretora',
            name='ambiente',
            field=models.CharField(blank=True, default='D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='aplicativo',
            field=models.CharField(blank=True, default='MetaTrader', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='capitalLig',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='moeda',
            field=models.CharField(blank=True, default='BRL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='saldo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='corretora',
            name='server',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custonresponse001',
            name='corretora',
            field=models.CharField(db_column=False, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custonresponse001',
            name='corretora_id',
            field=models.IntegerField(db_column=False),
        ),
        migrations.AlterField(
            model_name='custonresponse001',
            name='ordem_id',
            field=models.IntegerField(db_column=False),
        ),
        migrations.AlterField(
            model_name='custonresponse001',
            name='status',
            field=models.CharField(db_column=False, default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estrategias',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordemstatus',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='ambiente',
            field=models.CharField(blank=True, default='D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='nomeRobo',
            field=models.CharField(blank=True, default='RPBO0012', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='perfil',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='preco_compra',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='preco_gain',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='preco_loss',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='preco_venda',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='qtdContratos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='simbolo',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='status',
            field=models.CharField(blank=True, default='X', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordercompravenda',
            name='tipo',
            field=models.CharField(blank=True, default='X', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='periodo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='tipo',
            field=models.CharField(blank=True, default='X', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderenvio',
            name='valor',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
