# Generated by Django 3.2.8 on 2022-05-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_configuracoesporest'),
    ]

    operations = [
        migrations.AddField(
            model_name='custonresponse004',
            name='estr_id_id',
            field=models.IntegerField(blank=True, db_column=False, null=True),
        ),
    ]
