# Generated by Django 3.2.7 on 2021-12-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211216_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretora',
            name='usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
