# Generated by Django 3.2.8 on 2022-01-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_corretora_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='custonresponse005',
            name='ROBOENVIOORDEM',
            field=models.CharField(blank=True, db_column=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse005',
            name='ROBORECEBIMENTOORDEM',
            field=models.CharField(blank=True, db_column=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse005',
            name='ROBOUPDATEORDEM',
            field=models.CharField(blank=True, db_column=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='custonresponse005',
            name='ordem_dia',
            field=models.IntegerField(blank=True, db_column=False, null=True),
        ),
        migrations.AddField(
            model_name='ordercompravenda',
            name='positionId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderenvio',
            name='corretora_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.corretora'),
        ),
    ]
