# Generated by Django 3.2.7 on 2021-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_corretora_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretora',
            name='moeda',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
