# Generated by Django 3.2.8 on 2022-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220128_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustonResponse007',
            fields=[
                ('id', models.IntegerField(db_column=False, primary_key=True, serialize=False)),
                ('corretora_id', models.IntegerField(blank=True, db_column=False, null=True)),
                ('ticket', models.IntegerField(blank=True, db_column=False, null=True)),
                ('simbolo', models.CharField(blank=True, db_column=False, max_length=200, null=True)),
                ('qtdContratos', models.IntegerField(blank=True, db_column=False, null=True)),
                ('positionId', models.IntegerField(blank=True, db_column=False, null=True)),
                ('status', models.CharField(blank=True, db_column=False, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, db_column=False, max_length=200, null=True)),
            ],
        ),
    ]
