# Generated by Django 3.2.8 on 2022-01-28 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_custonresponse007'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemZerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='Z', max_length=1, null=True)),
                ('corretora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.corretora')),
                ('ordem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.orderenvio')),
            ],
        ),
    ]
