# Generated by Django 3.2.8 on 2022-01-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_ordemzerada'),
    ]

    operations = [
        migrations.AddField(
            model_name='custonresponse007',
            name='ordem_id_id',
            field=models.IntegerField(blank=True, db_column=False, null=True),
        ),
        migrations.AddField(
            model_name='ordemstatus',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
