# Generated by Django 3.2.8 on 2022-03-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220131_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('dataUltUp', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='Z', max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='estrategias',
            name='isteste',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlPrincipal', models.CharField(blank=True, max_length=255, null=True)),
                ('dataConf', models.DateTimeField(auto_now_add=True, null=True)),
                ('loteWin', models.FloatField(blank=True, default=0, null=True)),
                ('loteWdo', models.FloatField(blank=True, default=0, null=True)),
                ('loteB3', models.FloatField(blank=True, default='X', max_length=1, null=True)),
                ('gainDiario', models.FloatField(blank=True, default=0, null=True)),
                ('lossDiario', models.FloatField(blank=True, default=0, null=True)),
                ('lossWin', models.FloatField(blank=True, default=0, null=True)),
                ('gainWin', models.FloatField(blank=True, default=0, null=True)),
                ('lossWdo', models.FloatField(blank=True, default=0, null=True)),
                ('gainWdo', models.FloatField(blank=True, default=0, null=True)),
                ('lossB3', models.FloatField(blank=True, default=0, null=True)),
                ('gainB3', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('corretora_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.corretora')),
                ('robo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.robos')),
            ],
        ),
    ]
