# Generated by Django 3.2.8 on 2022-03-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220307_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='robos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='robos',
            name='dataUltUp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='robos',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
